# Generated by Django 5.0.7 on 2024-08-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaSLN', '0007_rename_con_dsapayout_payouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='loan_amount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dsapayout',
            name='loan_amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
