# Generated by Django 5.0.7 on 2024-09-10 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaSLN', '0009_dsa_dsa_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa_applications',
            name='dsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsaapp', to='dsaSLN.dsa'),
        ),
    ]
