# Generated by Django 5.0.7 on 2024-09-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaSLN', '0010_alter_dsa_applications_dsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsapayout',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dsa',
            name='dsa_password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dsa_applications',
            name='dsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsa', to='dsaSLN.dsa'),
        ),
    ]
