# Generated by Django 5.0.7 on 2024-09-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaSLN', '0011_dsapayout_date_alter_dsa_dsa_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comission',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
