# Generated by Django 5.0.7 on 2024-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaSLN', '0012_comission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
