# Generated by Django 5.0.7 on 2024-10-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaSLN', '0014_alter_dsapayout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsa',
            name='dsa_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
