# Generated by Django 5.0.7 on 2024-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsaSLN', '0016_comission_name_dsapayout_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comission',
            name='comissionPercentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dsapayout',
            name='comissionPercentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
